services:
  happy-server:
    image: happy-server:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/happy-server
      - REDIS_URL=redis://redis:6379
      - HANDY_MASTER_SECRET=${HANDY_MASTER_SECRET}
      - PORT=3000
      - METRICS_ENABLED=false
      - DANGEROUSLY_LOG_TO_SERVER_FOR_AI_AUTO_DEBUGGING=
      # S3/MinIO 配置 (可选，取消注释以启用文件存储)
      # - S3_HOST=minio
      # - S3_PORT=9000
      # - S3_USE_SSL=false
      # - S3_ACCESS_KEY=<写你的账号>
      # - S3_SECRET_KEY=<写你的密码，不少于8位>
      # - S3_BUCKET=happy
      # - S3_PUBLIC_URL=http://localhost:9000/happy
    ports:
      - "100.102.75.80:3000:3000"   # 配合 tailscale vpn ip
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      # minio:
      #   condition: service_started
    # Uses entrypoint.sh from Dockerfile (runs migration + starts server)
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=happy-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 不暴露给宿主机，避免 5432 冲突
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d happy-server -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7.2-alpine #改了一下，指定了版本，防止和另一个服务的redis完全相同
    restart: unless-stopped
    volumes:
      - redis_data:/data
    # 不暴露给宿主机，避免 6379 冲突
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
  # ========== S3/MinIO 服务 (可选，取消注释以启用文件存储) ==========
  # minio:
  #   image: minio/minio:latest
  #   command: server /data --console-address ":9001"
  #   restart: unless-stopped
  #   environment:
  #     MINIO_ROOT_USER: ${S3_ACCESS_KEY}         # 请改成强密码
  #     MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}     # 请改成强密码
  #   ports:
  #     - "127.0.0.1:9000:9000"   # S3 API
  #     - "127.0.0.1:9001:9001"   # Web 控制台
  #   volumes:
  #     - minio_data:/data
  #
  # # 启动后自动创建 bucket
  # minio-init:
  #   image: minio/mc:latest
  #   depends_on:
  #     minio:
  #       condition: service_started
  #   entrypoint: ["sh","-c"]
  #   environment:
  #     MINIO_ROOT_USER: ${S3_ACCESS_KEY}
  #     MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
  #     S3_BUCKET: ${S3_BUCKET}
  #   command:
  #     - >
  #       echo "[minio-init] alias..."; mc alias set local <http://minio:9000> "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" &&
  #       echo "[minio-init] waiting..."; until mc ready --json local >/dev/null 2>&1; do echo "[minio-init] still waiting..."; sleep 2; done &&
  #       echo "[minio-init] create bucket $S3_BUCKET"; mc mb -p local/$S3_BUCKET || true &&
  #       echo "[minio-init] set anonymous download"; mc anonymous set download local/$S3_BUCKET || true
  #   restart: "no"

volumes:
  postgres_data:
  redis_data:
  # minio_data:  # 取消注释以启用 MinIO 存储

